Traceback (most recent call last):
  File "/mnt/c/projects/Code/jupyter-book-test/wsl-jupyter-book/kick_tires_jb10/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/mnt/c/projects/Code/jupyter-book-test/wsl-jupyter-book/kick_tires_jb10/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/mnt/c/projects/Code/jupyter-book-test/wsl-jupyter-book/kick_tires_jb10/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/mnt/c/projects/Code/jupyter-book-test/wsl-jupyter-book/kick_tires_jb10/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/c/projects/Code/jupyter-book-test/wsl-jupyter-book/kick_tires_jb10/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/mnt/c/projects/Code/jupyter-book-test/wsl-jupyter-book/kick_tires_jb10/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/mnt/c/projects/Code/jupyter-book-test/wsl-jupyter-book/kick_tires_jb10/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from myst_nb import glue

fig, ax = plt.subplots()
N = 100
x = 5 + np.random.randn(N)
y = 3 + np.random.randn(N)

plt.plot(x,y,'o')
plt.xlabel('Feather Length [mm]')
plt.ylabel('Bone Diameter [cm]')
glue('random-fig',fig, display=False)

myVar = "42"
glue("myLabel", myVar, display=False )

m = np.mean(y)  # mean 
s = np.std(y)   # standard deviation
up = m+2*s      # 95% confidence level
low = m-2*s     # 5% confidence level

glue('avg',m, display=False)
glue('upper',up, display=False)
glue('lower',low, display=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-919da5ba8fbb>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mfrom[0m [0mmyst_nb[0m [0;32mimport[0m [0mglue[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mfig[0m[0;34m,[0m [0max[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0msubplots[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'numpy'
ModuleNotFoundError: No module named 'numpy'

